### ISSUE TITLE
swapcontext undefined

### ISSUE THREAD

**Issue by eosrc** [pahihu/picoLisp#2]
Making references to undefined function swapcontext (and two other functions with context in the name) in flow.c @pahihu

**Comment by pahihu** [comment]
What is your operating system and version ? On macOS it is required to define _XOPEN_SOURCE to compile it.

**Comment by eosrc** [comment]
Using a tablet with termux and Android 9.

**Comment by pahihu** [comment]
OK, Android does not have the ucontext functions.

Options:
- use Alexander Burger's newest pil21 on Termux (instructions at https://www.mail-archive.com/picolisp@software-lab.de/msg10216.html)
- try to compile https://github.com/kaniini/libucontext, which provides the missing items.
- I have modified the sources to disable the co/stack/yield functions on Android, which require them.
